/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export const Logo: React.FC<GroupProps> = (props, material) => {
  const { nodes } = useGLTF("/models/logo/logo3d.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes.Curve as any).geometry}
        material={material}
        scale={5.5}
      />
    </group>
  );
};

useGLTF.preload("/models/logo/logo3d.glb");
